routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('backend/login','SSOBrokerController@authenticateToSSO');
Route::get('backend/login','SSOBrokerController@authenticateToSSO');
Route::get('authenticateToSSO','SSOBrokerController@authenticateToSSO');
Route::get('authData/{authData}','SSOBrokerController@authenticateToSSO');
Route::get('logout/{sessionId}','SSOBrokerController@logout');
Route::get('changeRole/{role}', 'SSOBrokerController@changeRole')->name('changeRole');

Route::group(['middleware' => ['SSOBrokerMiddleware']], function () {
    Route::get('test', function(){
       return 'test';
    });
 });
 

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/home',BlogController::class);
Route::resource('/blog',BlogController::class);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $guarded = [
        'id','created_at','updated_at'
    ];

    protected $fillable = [
        'title', 'description', 'created_user_id', 'created_author_id', 'image'
    ];

    public function createdAuthor()
    {
        return $this->hasOne('App\Models\Author','id','created_author_id');
    }

    public function createdUser()
    {
        return $this->hasOne('App\Models\User','id','created_user_id');
    }
    
}

app/Http/Controllers/Api/BlogController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\BlogService;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Blog;
use Storage;

class BlogController extends Controller
{
    protected $BlogServices;
    public function __construct(
        BlogService $BlogService
    ) {
        $this->BlogService = $BlogService;
    }

    public function getData()
    {
        $blogs = $this->BlogService->getData();
        return $this->responSuccess(200, 'Success', $blogs);
    }

    public function create(Request $request)
    {
        $user = User::where('api_token')->first();

        
        $request['created_user_id'] = $user->id;
        $request['created_author_id'] = $user->id;

        $image = $request->file('image');
        $image->storeAs('/blogs', $image->hashName());

        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'image' => 'required'
        ], [
            'title.required' => 'title diperlukan !',
            'description.required' => 'description diperlukan !',
            'image.required' => 'image diperlukan !'
        ]);
        $blog = $this->BlogService->create($request->all());
        return $this->responSuccess(200, 'Blog Berhasil Ditambahkan !', $blog);
    }

    public function update(Request $request, Blog $blog)
    {
        {
            $token = $request->bearerToken();
            $user = User::where('api_token', $token)->first();
            if (empty($user)) {
                return $this->responAuthFailed(301, 'Anda tidak memiliki ijin !', 'Failed');
            }
    
            $request['created_user_id'] = $user->id;
                
            if ($request->file('image') == "") {
    
                //hapus old image
                Storage::disk('public')->delete('public/blogs/' . $blog->image);
    
                //upload new image
            }else {
                $image = $request->file('image');
                $image->storeAs('/blogs', $image->hashName());
            }
    
            $blog = $this->BlogService->update($request->all());
            return $this->responSuccess(200, 'Blog Berhasil Diupdate !', $blog);
        }
    }

    public function delete($id)
    {
        $blogs = $this->BlogService->delete($id);
        return $this->responSuccess(200, 'Success', $blogs);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\BlogService;
use App\Models\Blog;
use Storage;

class BlogController extends Controller
{
    protected $BlogService;
    function __construct(
        BlogService $BlogService
    ) {
        $this->BlogService = $BlogService;
    }

    public function index()
    {
        $blogs = $this->BlogService->getData();
        return view('blog.index', [
            'data_blogs' => $blogs
        ]);
    }

    public function create()
    {
        return view('blog.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title'     => 'required',
            'description'   => 'required',
            'created_user_id' => 'required',
            'created_author_id' => 'required',
            'image'     => 'required|image|mimes:png,jpg,jpeg'
            
            
        ]);

        //upload image
        $image = $request->file('image');
        $image->storeAs('/blogs', $image->hashName());

        $blog = Blog::create([
            'title'     => $request->title,
            'description'   => $request->description,
            'created_user_id'   => $request->created_user_id,
            'created_author_id'   => $request->created_author_id,
            'image'     => $image->hashName()
            
        ]);

        return redirect()->route('blog.index')->with('succes', 'Data Berhasil Disimpan');
    }

    public function show(Blog $blog)
    {
        return view('blog.show', compact('blog'));
    }

    public function edit(Blog $blog)
    {
        return view('blog.edit', compact('blog'));
    }

    public function update(Request $request, Blog $blog)
    {
        $this->validate($request, [
            'title'     => 'required',
            'description'   => 'required',
            'created_author_id'   => 'required',
            'created_user_id' => 'required'
        ]);

        //get data Blog by ID
        $blog = Blog::findOrFail($blog->id);

        if ($request->file('image') == "") {

            $blog->update([
                'title'     => $request->title,
                'description'   => $request->description,
                'created_author_id'     => $request->created_author_id,
                'created_user_id'     => $request->created_user_id
                
            ]);
        } else {

            //hapus old image
            Storage::disk('public')->delete('public/blogs/' . $blog->image);

            //upload new image
            $image = $request->file('image');
            $image->storeAs('/blogs', $image->hashName());

            $blog->update([
                'title'     => $request->title,
                'description'   => $request->description,
                'created_user_id' => $request->created_user_id,
                'created_author_id' => $request->created_author_id,
                'image'     => $image->hashName()
            ]);

            return redirect()->route('blog.index')->with('succes', 'Data Berhasil Diupdate');
        }
    }

    public function destroy(Blog $blog)
    {
        $blog->delete();

        return redirect()->route('blog.index')->with('succes', 'Data Berhasil Dihapus');
    }
}

resources/views/blog/create.blade.php
@extends('blog/template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Create New Blog</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('blog.index') }}"> Kembali</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> Input gagal.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="font-weight-bold">JUDUL :</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" placeholder="Masukkan Judul Blog">

                <!-- error message untuk title -->
                @error('title')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
                @enderror
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="font-weight-bold">Deskripsi :</label>
                        <input type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" placeholder="Masukkan Deskripsi">

                        <!-- error message untuk title -->
                        @error('description')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Dibuat Oleh :</label>
                                <input type="text" class="form-control @error('created_user_id') is-invalid @enderror" name="created_user_id" value="{{ old('created_user_id') }}" placeholder="Masukkan ID Pengguna">

                                <!-- error message untuk title -->
                                @error('created_user_id')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                                <label class="font-weight-bold">Penulis :</label>
                                                <input type="text" class="form-control @error('created_author_id') is-invalid @enderror" name="created_author_id" value="{{ old('created_author_id') }}" placeholder="Masukkan ID Penulis">

                                                <!-- error message untuk title -->
                                                @error('created_author_id')
                                                <div class="alert alert-danger mt-2">
                                                    {{ $message }}
                                                </div>
                                                @enderror
                                            </div>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label class="font-weight-bold">Gambar :</label>
                                        <input type="file" class="form-control @error('image') is-invalid @enderror" name="image">

                                        @error('image')
                                        <div class="alert alert-danger mt-2">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                                                <button type="reset" class="btn btn-md btn-warning">RESET</button>
                                            </div>
                                            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                                            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</form>
@endsection

resources/views/blog/edit.blade.php
@extends('blog/template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Edit Blog</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('blog.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('blog.update',$blog->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Judul :</strong>
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $blog->title) }}" placeholder="Masukkan Judul Blog">

                <!-- error message untuk title -->
                @error('title')
                <div class="alert alert-danger mt-2">
                    {{ $message }}
                </div>
                @enderror
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Deskripsi :</strong>
                        <input type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description', $blog->description) }}" placeholder="Masukkan Deskripsi">

                        <!-- error message untuk title -->
                        @error('description')
                        <div class="alert alert-danger mt-2">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Dibuat Oleh :</strong>
                                <input type="text" class="form-control @error('created_user_id') is-invalid @enderror" name="created_user_id" value="{{ old('created_user_id', $blog->created_user_id) }}" placeholder="Masukkan Nama Pengguna">

                                <!-- error message untuk title -->
                                @error('created_user_id')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Penulis :</strong>
                                        <input type="text" class="form-control @error('created_author_id') is-invalid @enderror" name="created_author_id" value="{{ old('created_author_id', $blog->created_author_id) }}" placeholder="Masukkan Nama Penulis">

                                        <!-- error message untuk title -->
                                        @error('created_author_id')
                                        <div class="alert alert-danger mt-2">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label class="font-weight-bold">GAMBAR</label>
                                        <input type="file" class="form-control" name="image">
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                                                <button type="reset" class="btn btn-md btn-warning">RESET</button>
                                            </div>
                                        </div>

</form>
@endsection

resources/views/blog/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <title>CRUD BLOG</title>
</head>

<body>
    <div class="container mt-5">
        <div class="float-right">
            <a class="btn btn-success" href="{{ route('blog.create') }}"> Input Blog</a>
        </div>
        <table id="myTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Judul</th>
                    <th>Deskripsi</th>
                    <th>Dibuat Oleh</th>
                    <th>Penulis</th>
                    <th>Gambar</th>
                    <th width="200px" class="text-center">Action</th>
                </tr>
            <tbody>
                @foreach ($data_blogs as $i => $blog)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $blog->title }}</td>
                    <td>{{ $blog->description }}</td>
                    <td>{{ $blog->createdUser->name }}</td>
                    <td>{{ $blog->createdAuthor->name }}</td>
                    <td class="text-center">
                        <img src="{{ asset('storage/blogs/'.$blog->image) }}" class="rounded" style="width: 150px">
                    </td>


                    <td class="text-center">
                        <form action="{{ route('blog.destroy',$blog->id) }}" method="POST">

                            <a class="btn btn-info btn-sm" href="{{ route('blog.show',$blog->id) }}">Show</a>

                            <a class="btn btn-primary btn-sm" href="{{ route('blog.edit',$blog->id) }}">Edit</a>

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            </thead>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>

</html>

resources/views/blog/show.blade.php
@extends('blog/template')

@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2> Show Blog</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('blog.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="col">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Judul :</strong>
            <input type="text" name="title" class="form-control" value="{{ $blog->title }}" readonly>
        </div>
    </div>

    <div class="col">
        <div class="col-xs-100 col-sm-100 col-md-100">
            <div class="form-group">
                <strong>Description :</strong>
                <input type="text" name="description" class="form-control" value="{{ $blog->description }}" readonly>
            </div>
        </div>

        <div class="coloumn">
            <div class="col-xs-200 col-sm-200 col-md-200">
                <div class="form-group">
                    <strong>Dibuat Oleh:</strong>
                    <input type="text" name="createdUser->name" class="form-control" value="{{ $blog->createdUser->name }}" readonly>
                </div>
            </div>

            <div class="coloumn">
                <div class="col-xs-200 col-sm-200 col-md-200">
                    <div class="form-group">
                        <strong>Penulis :</strong>
                        <input type="text" name="createdAuthor->name" class="form-control" value="{{ $blog->createdAuthor->name }}" readonly>
                    </div>
                </div>

                <div class="coloumn">
                    <div class="col-xs-200 col-sm-200 col-md-200">
                        <div class="form-group">
                            <strong>Gambar :</strong>
                            <td class="text-center">
                                <input type="text" name="image" class="form-control" value="{{ $blog->image }}" readonly>
                            </td>
                        </div>
                    </div>
                </div>
                @endsection

resources/views/blog/template.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Tutorial CRUD Laravel 8 untuk Pemula</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container" styles="margin-top:10px">
    @yield('content')
</div>

</body>
</html>